name: Weekly Scraper

on:
  schedule:
    - cron: '0 0 * * 1'   # 毎週月曜 0:00 UTC に実行（必要に応じて調整）
  workflow_dispatch:      # 手動実行も可能

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: Pythonのセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 依存パッケージのインストール
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pandas

      - name: スクレイパーの実行
        run: python scraper.py

      - name: CSV成果物のアップロード
        uses: actions/upload-artifact@v4.6.1
        with:
          name: scraped-data
          path: data.csv